spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  Application: JavaWebApp
  Active:
    profile: dev  
    
server: 
  port: 8081    